dominikbraun/timetrace

cli/status.go
core/record.go
core/timetrace.go
fs/fs.go

Fixes #4. With this PR, the tracked time displayed with `timetrace status` is only calculcated using `time.Now()` if it hasn't ended.

Only calculate time for current record if it hasn't ended

---

fs/fs.go

Fixes #8.
This will allow project keys to contain slashes and back-slashes, which would normally cause problems when they're part of the filepath.

Sanitize project key when requesting a project filepath

---

core/record.go
core/timetrace.go

This PR fixes the calculation of the total tracked time when calling `timetrace status`.

Fix calculation of total tracked time

---

README.md
cli/list.go
core/record.go

This PR adds a new command - `timetrace list records` for listing all records of a given date.

Implement `timetrace list records` command

---

fs/fs.go

As stated in the issue I added a func returning the init dir for the empty records directory and appended the slice in fs.EnsureDirectories accordingly. func recordsInitSubDir returns `~/.timetrace/records/YYYY-MM-DD`. cmd timetrace status exists now with ErrTrackingNotStarted instead of with the err from ioutil.ReadDir.

closes #14: added func returning init dir for empty records dir

---

cli/status.go
core/timetrace.go
core/timetrace_test.go

Added two functions on the Report struct which format the duration according to the discussion in the issue. Both functions return the result of `formatDuration` which does the actual formatting. Tests of this function are included.
```
+-----------------+--------------------+--------------+
| CURRENT PROJECT | WORKED SINCE START | WORKED TODAY |
+-----------------+--------------------+--------------+
| timetest        | 0h 0min 5sec       | 1h 6min      |
+-----------------+--------------------+--------------+
```
And over one minute
```
+-----------------+--------------------+--------------+
| CURRENT PROJECT | WORKED SINCE START | WORKED TODAY |
+-----------------+--------------------+--------------+
| timetest        | 0h 1min            | 1h 7min      | …
```

closing #6 formating of duration for table output.

---

cli/list.go

Adds the project name to each record row when you list the records
`timetrace list records YYYY-MM-DD`:
This resolves #23

Add the project name to the output of list records

---

README.md
cli/delete.go
cli/get.go
cli/root.go

This PR adds the command  - `timetrace delete record <YYYY-MM-DD-HH-MM>` for deleting a  record by its start time. And it closes #13

13 delete record command

---

autocompletion/bash/enable.sh
autocompletion/bash/timetrace.sh
out/out.go

This pull request enable bash autocompletion for the CLI. The autocompletion would be triggered when the key <TAB> is pressed; for example:
```bash
timetrace <TAB>
```
If we press <TAB> here, the autocompletion would suggest all the commands on the CLI. Like in the following gif.
To allow this behavior the user would run the following command:
```bash
source autocompletion/bash/enable.sh
```

Enabling bash autocompletion for the CLI

---

cli/list.go
cli/list_test.go

Add a --billable (-b) flag to `timetrace list records` to only display the billable records
closes #21

List billable records

---

cli/version.go

This pull request resolves #12 . As stated in #12, running `timetrace version` now uses `out.Info` to print the version information.

Print CLI version using out.Info

---

out/out.go

This PR adds padding to the headers used in out.Table, in response to issue #43

added function to pad headers, updated out.Table to pad headers

---

out/out.go

This PR add the `tablewriter.BgMagentaColor` to the list of header colors.

Add magenta header color

---

Dockerfile

Fix the Dockerfile description. It was probably just left in from a copy and paste

Fix the Dockerfile description label

---

cli/delete.go
cli/get.go

This PR updates the command argument syntax for 'get record' and 'delete record', based on the config.yaml, as per issue #17

17 cmd arg syntax

---

README.md

Since timetrace is officially still in `devmode`, the `--devmode` flag is required for the Snap installation.

Add `--devmode` to Snap installation instruction

---

cli/edit.go
core/record.go

I implemented the edit record command as mentioned here: https://github.com/dominikbraun/timetrace/issues/19
As of now, there is no check if the end time contradicts with the start time of another record (still an open question), but the command returns an error if the new end time is before the start time of the record.

implement timetrace edit record command

---

cli/delete.go
cli/edit.go
cli/get.go
cli/list.go
core/formatter.go

With this PR, existing code that checks the `Config.Use12Hours` field and set the date/time layout manually will be replaced with calls to `core.Formatter`.

Migrate to `core.Formatter` for retrieving the configured time formats

---

core/record.go

closes #68 
- Throw `record is still in progress` error on trying to edit incomplete record
- Refactor common logic into `editRecord` method

Handle editing of incomplete record

---

cli/status.go

This PR resolves issue #64 by changing the error message to an info message, if a user has not tracked any time today.

changed how 'timetrace status' informs the user that they haven't tracked time today

---

cli/edit.go
core/record.go
core/timetrace.go

closes #71
I implemented the `latest` alias for `edit record` by writing a new method `GetLatestRecord` in record.go. 
Since the fs-methods return sorted slices, it should be ensured that the last element of the slice is also the last created record.
If there are no records created yet, an error is returned.

Add latest alias to `edit record` command

---

cli/list.go
cli/list_test.go

With this PR, the `--project` filter will take project modules into account - meaning a module `grind-beans@make-coffee` will be included when passing a filter `--project make-coffee`.

Consider modules when filtering projects

---

cli/list.go
core/project.go

closes #60 
I added a new method ListProjectModules that uses loadProjectModules to create a string with all the modules of a project. 
They will be printed out on `timetrace list projects`
But there is a problem with this solution: Modules, that are created for a non-existent parent-project are not listed at all. Therefore, I would propose that we prevent users from creating modules for non-existent projects.

Display project modules

---

core/project.go

closes #72 
i added a method to check if the parent of a module exists before creating it. 
the create-command now returns an error if it does not exist.

added method to check if parent project exists for module

---

core/record.go
core/timetrace.go

Resolves issue #95 by checking that the latest directory contains at least 1 file.

fixed issue with attempting to load data from an empty directory

---

cli/list.go
cli/list_test.go
core/formatter.go
core/timetrace_test.go
out/out.go

This PR closes #58. Notable changes in this pull request are:
* Making `formatter.FormatDuration` public
PTAL @dominikbraun

Total tracked time

---

core/formatter.go

In the time formatter package, if `hours` and `minutes` are 0 then `seconds` will be considered. As seconds is not handled in users perspective, `seconds` need not be considered.

[Patch] Remove seconds from Time Formatter

---

cli/status.go

Initial very basic implementation for #109 
I didn't write any test and actually used `fmt.Printf`  should I create an `out.Printf` or something like this?
Please any suggestions are welcome, I am not really a golang dev =P
To have better options to replace and format, we would need to add more information to the status command.

Add basic format option

---

cli/status.go

I noticed that two formatting variables had a slighty different name than the struct fields. I thought it would be nice if those names were the same:
https://github.com/dominikbraun/timetrace/blob/b4b7c153e92cd869ac34e92fedc0d6a16460862c/core/timetrace.go#L18-L22
This PR fixes that.

Rename formatting variables for `--format` flag

---

README.md

This PR adds the `--format` flag as well as instructions for integrating timetrace into Starship to the docs.

Add --format flag and Starship integration to README.md

---

README.md
cli/status.go

Resolves #128.
This PR also introduces a `statusReport` type that stores all printed strings. It is initialized with the relevant values, and the individual formatting and output options just use that instance for printing the status.

Implement `--output` flag for `timetrace status`

---

cli/create.go
core/formatter.go
core/timetrace.go
core/timetrace_test.go

closes #97
I added the create record command. I also added checks that return an error if the end time is before the start time or the record collides with other records of the same day.

add create record command

---

README.md
cli/report.go

since the `timetrace status` command already specifies a naming convention for what `--output` and `--format` flags are supposed to do - the `report` command had to change accordingly.

resolved naming convention issue from #137

---

cli/delete.go

This PR addresses #110.
- `askForConfirmation()` now defaults to no unless the input is specifically "y" or "Y".
- added `askForConfirmation()` to `deleteProjectCommand`

timetrace delete commands: Default to no when asking for confirmation

---

core/timetrace.go
core/timetrace_test.go

PR for #145 
Changes: 
- Fixing issue with nil pointer dereference during collides check against tracked record
- Simplified collides check conditions (here's a good reference for it: [Date ranges overlap check](https://stackoverflow.com/questions/325933/determine-whether-two-date-ranges-overlap))
- Added missing test cases for complete records and new ones for records that are being tracked

#145 handle nil pointer dereference for tracked record

---

cli/create.go

PR for #151 
Added validation to `create` command to check if provided record happend after current timestamp.

#151 create record validation if it is happened in future

---

cli/report.go
core/reporter.go
core/reporter_test.go

closing #140 
sample output:
```
// no filter by module but project has multiple modules
+-----------+----------+-----------------------+---------+-------+------------+-----------+
|  PROJECT  |  MODULE  |         DATE          |  START  |  END  |  BILLABLE  |   TOTAL   |
+-----------+----------+-----------------------+---------+-------+------------+-----------+
| test      | mod1     | Sunday, 27. June 2021 | 18:11   | 18:11 | no         |           |
+           +----------+-----------------------+---------+-------+------------+-----------+
|           | mod1     | Sunday, 27. June 2021 | 21:53   | 22:53 | no         |           |
+           +----------+-----------------------+---------+-------+------------+-----------+
|           | mod2     | Sunday, 27. June 2021 | 21:54   | 22:54 | …
```

Report filter module #140

---

core/record.go

- As discussed in the issue https://github.com/dominikbraun/timetrace/issues/163, changing `ListRecords` to call the function `loadAllRecords` as the implementation is the same. 
Issue: https://github.com/dominikbraun/timetrace/issues/163

cleanup duplicate code for list records function

---

core/record.go
core/timetrace.go

Since the func `loadFromRecordDir` has changed its behaviour I double checked that there are no other places the function is currently used. For future reference I included a comment stating that the func will ignore `.bak` files.
closes point (2) from #161

added ignore case for loading records if file has a .bak extension

---

cli/create.go
core/timetrace.go
core/timetrace_test.go

resolve #173 
first PR in this repo
I simply changed/added some print statements
any feedback will be appreciated
now the output is
```
❯ go run . create record open-summer today 8:25 10:30
❗ collides with these records :
💡 open-summer 2021-08-28 08:21:00 +0800 CST-2021-08-28 09:23:00 +0800 CST
💡 open-summer 2021-08-28 09:30:00 +0800 CST-2021-08-28 10:20:00 +0800 CST
⚠️  start and end of the record should not overlap with others
```

print more info when created record collides with others

---

cli/edit.go
cli/list.go
core/record.go

closes #116
I implemented the features discussed in #116, but I needed to change the "marker" of the ID from `#` to `*`. Otherwise, the argument seems to be ignored. I don't know if it's my terminal or the go library or something else, but the `arg[0]` is empty when the input starts with a `#`. 
This begs two questions: Are you okay with the `*` as a marker, or would you prefer something else? And should we change the header of the list record command accordingly, to avoid confusion?

Simplify record keys

---

cli/list.go
cli/start.go
core/formatter.go
core/formatter_test.go
core/record.go
core/timetrace.go

Add basic supports for adding tags

---

cli/edit.go

This PR adds a fix to check if a time collision happens before enabling editing the record.
Fixes #187

Check record collisions before editing a record

---

cli/create.go

Fixes #190.
Using `Use12Hours` in `core.Timetrace.Config()` to use a different string for the usage help text for `timetrace create record`.
```txt
Create a new record
timetrace create record <PROJECT KEY> {<YYYY-MM-DD>|today|yesterday} <HH:MM> <HH:MM> [flags]
Flags:
-b, --billable   mark tracked time as billable
-h, --help       help for record
```
```txt
Create a new record
timetrace create record <PROJECT KEY> {<YYYY-MM-DD>|today|yesterday} <HH:MMPM> <HH:MMPM> [flags]
Flags:
-b, --billable   mark tracked time as billable
-h, --help       help for record
```

Change help text for `timetrace create record` to honor `use12hours`

---

cli/start.go

Limits the number of tags to 3 for timetrace start
Fix #188

limit number of tags to 3

---

core/formatter.go

`timetrace` doesn't report days, and even if it did, the modulo should be 24, not 60. This almost caused me a heart attack! 😆

Remove modulo on hours in reports

---

cli/status.go

When using a format string, `BreakTimeToday` is used instead of `TrackedTimeToday` for `{trackedTimeToday}`. I have not uploaded a rebuilt binary.

Fix typo for {trackedTimeToday} replacement

---

README.md

As [this](https://scoop-docs.vercel.app/docs/concepts/Buckets.html#installing-from-other-buckets) suggests, you need to provide a name when adding a bucket:
`scoop bucket add <name-of-bucket> <location-of-git-repo>`

Modify installation command using scoop
